name: Clojure CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein -U deps
    - name: Setup test config
      run: 'echo "$TEST_CONFIG" > test-resources/test-config.edn'
      env:
        TEST_CONFIG: ${{ secrets.TEST_CONFIG }}
    - name: Setup test service account
      run: 'echo "$TEST_SERVICE_ACCOUNT" > test-resources/service-account.json'
      env:
        TEST_SERVICE_ACCOUNT: ${{ secrets.TEST_SERVICE_ACCOUNT }}
    - name: Run tests
      run: lein test
    - name: Deploy snapshots
      if: github.ref == 'refs/heads/devel'
      run: lein deploy
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
